### ISSUE TITLE
add getpass function to the program

### ISSUE THREAD

**Issue by git-flan828** [CarouselIndustries/Infrastructure-Code#1]
# TODO Change password method to getpass()
# Get username/password
username = input('Enter the username: ')
password = input('Enter the password: ')
secret = None

**Comment by git-flan828** [comment]
'from getpass import getpass
#1  Possible get pass. 
    username = str(raw_input("Please enter the username: "))
    # secure way to get the password.
    passwd = getpass('Please enter the password: '	)

remove 
username = input('Enter the username: ')
password = input('Enter the password: ')
secret = None

change 
        device_dict = {
            'host': ip,
            'username': username,
            'password': password,
            'secret': secret,
            'device_type': 'cisco_ios'
        }
to 
        device_dict = {
            'host': ip,
            'username': username,
            'password': passwd,
            'secret': secret,
            'device_type': 'cisco_ios'
        }'

**Comment by jonviveiros** [comment]
Resolved in commit: 4e7e51c on 2020-07-20. getpass method confirmed as functional
